# Generated by Django 3.2.7 on 2021-11-07 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='nft/')),
                ('resized_image_path', models.CharField(blank=True, max_length=300)),
                ('is_for_sale', models.BooleanField()),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('create_time', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_owner', to=settings.AUTH_USER_MODEL)),
                ('original_owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_owner', to=settings.AUTH_USER_MODEL)),
                ('previous_owners', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buying_power', models.DecimalField(decimal_places=2, default=100.0, max_digits=65)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_buyer', to=settings.AUTH_USER_MODEL)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_nft', to='non_fungible_tartan.nft')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(default='no_preview_available.jpeg', upload_to='profiles/')),
                ('description', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('highest', models.BooleanField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='non_fungible_tartan.auction')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_nft', to='non_fungible_tartan.nft'),
        ),
        migrations.AddField(
            model_name='auction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auction_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
